name: ayoubMah

description: SC student

avatar: https://avatars.githubusercontent.com/u/158788525?s=400&u=7c6a0987fdf8b8c90fb20d56c0e099e993a7f411&v=4

footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: ayoubMah
  instagram:
  linkedin: ayoub-el-mahjouby
  pinterest:
  rss:
  twitter: MahjoubyA51471
  stackoverflow:
  youtube:
  googleplus:

disqus:

google_analytics:

url:

baseurl: ""

permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: compressed

gems:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME